---
- name: Create kubernetes directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "/etc/karmada"
    - "{{ local_release_dir }}"

- name: Slurp karmada apiserver config
  slurp:
    src: "{{ item }}"
  with_items:
    - "/etc/karmada/kubeconfig"
  register: karmada_config
  delegate_to: "{{ groups['karmada-controlplane'][0] }}"
  run_once: true

- name: write out karmada apiserver config
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0600
  no_log: true
  register: config
  with_items: "{{ karmada_config.results }}"
  when: inventory_hostname in groups['karmada-member']

- name: Slurp karmada host config
  slurp:
    src: "{{ item }}"
  with_items:
    - "/etc/karmada/config"
  register: karmada_config
  delegate_to: "{{ groups['karmada-controlplane'][0] }}"
  run_once: true

- name: Write out karmada host config
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0600
  no_log: true
  register: config
  with_items: "{{ karmada_config.results }}"
  when: inventory_hostname in groups['karmada-member']

- name: Get member cluster name
  command: "{{ bin_dir }}/kubectl config view --output  jsonpath='{.clusters[0].name}'"
  register: member_name
  changed_when: false

- name: Get member cluster user name
  command: "{{ bin_dir }}/kubectl config view --output  jsonpath='{.users[0].name}'"
  register: member_user
  changed_when: false

- name: Get member cluster context
  command: "{{ bin_dir }}/kubectl config current-context"
  register: context
  changed_when: false

- name: Delete context
  command: "{{ bin_dir }}/kubectl config delete-context {{ context.stdout }}"
  changed_when: false

- name: Set context
  command: "{{ bin_dir }}/kubectl config set-context {{ current_member_cluster_name }} --cluster={{ current_member_cluster_name }} --user=admin"
  changed_when: false

- name: Use context
  command: "{{ bin_dir }}/kubectl config use-context {{ current_member_cluster_name }}"
  changed_when: false

- name: reset member cluster name
  command: "sed -i 's/name: {{ member_name.stdout }}/name: {{ current_member_cluster_name }}/g'  /root/.kube/config"
  changed_when: false

- name: reset member cluster user name
  command: "sed -i 's/- name: {{ member_user.stdout }}/- name: admin/g'  /root/.kube/config"
  changed_when: false

- name: Create karmada apiserver config by secret
  shell: "{{ bin_dir }}/kubectl config current-context --kubeconfig=/etc/karmada/admin.conf"  # noqa 301 306 303 305
  register: karmada_apiserver
  delegate_to: "{{ groups['karmada-controlplane'][0] }}"

- name: Set fact of karmada agent
  set_fact:
    karmada_context: "{{ karmada_apiserver.stdout }}"
    # member_cluster_name: "{{ karmada_cluster.stdout | split('.') | last }}"
    member_cluster_name: "{{ current_member_cluster_name }}"
