---
- name: Get kubernetes master node certificate
  slurp:
    src: /etc/karmada/pki/{{ item }}
  with_items:
  - admin.crt
  - admin.key
  - apiserver.crt
  - apiserver.key
  - apiserver-kubelet-client.crt
  - apiserver-kubelet-client.key
  - ca.crt
  - ca.key
  - front-proxy-ca.crt
  - front-proxy-ca.key
  - front-proxy-client.crt
  - front-proxy-client.key
  - kube-controller-manager.crt
  - kube-scheduler.crt
  - kube-scheduler.key
  - sa.key
  - sa.pub
  register: kubernetes_master_certs
  run_once: true
  delegate_to: "{{ groups['karmada-controlplane'][0] }}"

- name: Distribute kubernetes master certificate to master node
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ kubernetes_master_certs.results }}"
  when:
  - inventory_hostname != groups['karmada-controlplane'][0]
  - inventory_hostname in groups['karmada-controlplane']
