---
- name: Read etcd-ca certificate private key stat info
  stat:
    path: /etc/karmada/pki/etcd/ca.key
  register: etcd_ca_key_stat

- name: Read etcd-ca root certificate stat info
  stat:
    path: /etc/karmada/pki/etcd/ca.crt
  register: etcd_ca_crt_stat

- name: Read healthcheck-client certificate private key stat info
  stat:
    path: /etc/karmada/pki/etcd/healthcheck-client.key
  register: etcd_healthcheck_client_key_stat

- name: Read server certificate private key stat info
  stat:
    path: /etc/karmada/pki/etcd/server.key
  register: etcd_server_key_stat

- name: Read peer certificate private key stat info
  stat:
    path: /etc/karmada/pki/etcd/peer.key
  register: etcd_peer_key_stat

- name: Read apiserver-etcd-client certificate private key stat info
  stat:
    path: /etc/karmada/pki/apiserver-etcd-client.key
  register: apiserver_etcd_client_key_stat
