---
- name: Create Karmada agent directory
  file: name=/etc/karmada state=directory

- name: Slurp karmada apiserver config
  slurp:
    src: "{{ item }}"
  with_items:
    - "/etc/karmada/kubeconfig"
  register: karmada_config
  delegate_to: "{{ groups['karmada-controlplane'][0] }}"
  run_once: true

- name: Write out karmada apiserver config
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0600
  no_log: true
  register: config
  with_items: "{{ karmada_config.results }}"
  when: inventory_hostname in groups['karmada-member']
