---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmada-aggregated-apiserver
  namespace: karmada-system
  labels:
    app: karmada-aggregated-apiserver
    apiserver: "true"
spec:
  selector:
    matchLabels:
      app: karmada-aggregated-apiserver
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        app: karmada-aggregated-apiserver
        apiserver: "true"
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - ""
      automountServiceAccountToken: false
      containers:
        - name: karmada-aggregated-apiserver
          image: wr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:{{ karmada_version }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: k8s-certs
              mountPath: /etc/karmada/pki
              readOnly: true
            - name: kubeconfig
              readOnly: true
              mountPath: /etc/karmada/kubeconfig
          command:
            - /bin/karmada-aggregated-apiserver
            - --kubeconfig=/etc/karmada/kubeconfig
            - --authentication-kubeconfig=/etc/karmada/kubeconfig
            - --authorization-kubeconfig=/etc/karmada/kubeconfig
            - --karmada-config=/etc/karmada/kubeconfig
            - --etcd-servers={{ karmada_etcd_endpoints }}
            - --etcd-cafile=/etc/karmada/pki/etcd/ca.crt
            - --etcd-certfile=/etc/karmada/pki/apiserver-etcd-client.crt
            - --etcd-keyfile=/etc/karmada/pki/apiserver-etcd-client.key
            - --tls-cert-file=/etc/karmada/pki/apiserver.crt
            - --tls-private-key-file=/etc/karmada/pki/apiserver.key
            - --audit-log-path=-
            - --feature-gates=APIPriorityAndFairness=false
            - --audit-log-maxage=0
            - --audit-log-maxbackup=0
          resources:
            requests:
              cpu: 100m
      volumes:
        - hostPath:
            path: /etc/karmada/pki
            type: DirectoryOrCreate
          name: k8s-certs
        - hostPath:
            path: /etc/karmada/kubeconfig
            type: FileOrCreate
          name: kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name: karmada-aggregated-apiserver
  namespace: karmada-system
  labels:
    app: karmada-aggregated-apiserver
    apiserver: "true"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: karmada-aggregated-apiserver
